### ISSUE TITLE
[Bug]: <title>请问通义的api key是从阿里哪个平台获取的啊？

### ISSUE THREAD

**Issue by Rorschaaaach** [guoyao/graphrag-more#1]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

我从阿里百炼平台拿的api key然后抽取实体时报错：
Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-9317d***********************8267. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
配置直接复制老哥的，让我去openai找key。。。是不是我哪里搞错了

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by guoyao** [comment]
通义的api key从这里获取：https://bailian.console.aliyun.com/?apiKey=1#/api-key
